### ISSUE TITLE
Some Recount problems

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI_AddOnSkins#23]
As you can see on the screenshot the small icons to reset, choose fight and post recount have some spacing which looks not so good. Embed Settings are disabled because of issue #11 .
The config window is a mix between skinned elements and original elements which looks also not good.
![wowscrnshot_091417_113245](https://user-images.githubusercontent.com/6052285/30422628-d0bd6eb8-9940-11e7-826e-68afd3ce5204.jpg)

**Comment by Crumdidlyumshis** [comment]
The buttons on the config are very very hard to skin. I may lean on @Loaal to figure this one out. Otherwise, it's not possible. It is the way the original author of recount built his buttons, which is not a standard way of doing so. @Apollyonn and I tried and I still try every now and then. 

As for the buttons on the recount, try latest update.

**Comment by fatlus** [comment]
With the latest update the spacing between the three buttons is correct. But I disabled the two forward/previous buttons and now there are blank spaces for these two buttons
