### ISSUE TITLE
Skada option in Embed Settings

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI_AddOnSkins#7]
There is no Skada addon in TBC, so the option is obsolete.

**Comment by Crumdidlyumshis** [comment]
Maybe we could replace it with https://github.com/Geigerkind/DPSMateTBC

**Comment by fatlus** [comment]
Would be a reasonable option but a Skada backport would be also awesome :D

**Comment by Arcitec** [comment]
Just adding in case anyone sees this ticket: Backporting is probably a bad idea. Skada uses low CPU, but achieves that by using lots of memory, by logging raw combat data instead of processing it in real-time. And The Burning Crusade client sucks at addons that use lots of memory (it can crash the game; out of memory error).
